package com.example.jaxws.ws.testwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.8
 * 2023-01-27T23:14:42.494+01:00
 * Generated source version: 3.3.8
 *
 */
@WebService(targetNamespace = "http://testwsdl.ws.jaxws.example.com", name = "testWsdlPortType")
@XmlSeeAlso({com.example.jaxws.ws.testwsdl.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestWsdlPortType {

    @WebMethod
    @WebResult(name = "testWsdlResp", targetNamespace = "http://bean.testwsdl.ws.jaxws.example.com", partName = "resp")
    public com.example.jaxws.ws.testwsdl.bean.TestWsdlResp testWsdl(

        @WebParam(partName = "req", name = "testWsdlReq", targetNamespace = "http://bean.testwsdl.ws.jaxws.example.com")
        com.example.jaxws.ws.testwsdl.bean.TestWsdlReq req
    ) throws SrvEx;
}
