package com.example.jaxws.ws.testwsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.8
 * 2023-01-27T23:14:42.512+01:00
 * Generated source version: 3.3.8
 *
 */
@WebServiceClient(name = "TestWsdl",
                  wsdlLocation = "classpath:test-wsdl.wsdl",
                  targetNamespace = "http://testwsdl.ws.jaxws.example.com")
public class TestWsdl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://testwsdl.ws.jaxws.example.com", "TestWsdl");
    public final static QName TestWsdlPortTypePort = new QName("http://testwsdl.ws.jaxws.example.com", "testWsdlPortTypePort");
    static {
        URL url = TestWsdl.class.getClassLoader().getResource("test-wsdl.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(TestWsdl.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:test-wsdl.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWsdl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWsdl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWsdl() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestWsdl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestWsdl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestWsdl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestWsdlPortType
     */
    @WebEndpoint(name = "testWsdlPortTypePort")
    public TestWsdlPortType getTestWsdlPortTypePort() {
        return super.getPort(TestWsdlPortTypePort, TestWsdlPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWsdlPortType
     */
    @WebEndpoint(name = "testWsdlPortTypePort")
    public TestWsdlPortType getTestWsdlPortTypePort(WebServiceFeature... features) {
        return super.getPort(TestWsdlPortTypePort, TestWsdlPortType.class, features);
    }

}
