package com.example.jaxws.ws.testwsdl2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.8
 * 2023-01-27T23:38:25.324+01:00
 * Generated source version: 3.3.8
 *
 */
@WebService(targetNamespace = "http://testwsdl2.ws.jaxws.example.com", name = "testWsdl2PortType")
@XmlSeeAlso({com.example.jaxws.ws.testwsdl2.bean.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TestWsdl2PortType {

    @WebMethod
    @WebResult(name = "testWsdl2Resp", targetNamespace = "http://bean.testwsdl2.ws.jaxws.example.com", partName = "resp")
    public com.example.jaxws.ws.testwsdl2.bean.TestWsdl2Resp testWsdl2(

        @WebParam(partName = "req", name = "testWsdl2Req", targetNamespace = "http://bean.testwsdl2.ws.jaxws.example.com")
        com.example.jaxws.ws.testwsdl2.bean.TestWsdl2Req req
    ) throws SrvEx;
}
